version: '3.8'

services:
  db:
    image: arm64v8/postgres:17.4-alpine
    container_name: postgres-db-string-index
    environment:
      POSTGRES_DB: string_index
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - string_index
    volumes:
      - string-index-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: social-go
    environment:
      - APP_ADDRESS=localhost:8080
      - DB_HOST=postgres-db-string-index
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      - DB_NAME=string_index
      - ENVIRONMENT=development
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - string_index

networks:
    string_index:
        driver: bridge

volumes:
  string-index-data:
