version: '3.8'

services:
  db:
    image: arm64v8/postgres:17.4-alpine
    container_name: postgres-db-social
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - string_index
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: social-go
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - string_index
